name: URL Health Check

on:
  schedule:
    - cron: "30 11 * * *"

  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the url
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-jj71.onrender.com/health
          max-attempts: 3
          retry-delay: 10s
